name: Upflux Web Client Pipeline

on:
  push:
    branches:
      - main  # Trigger on merge to the main branch
    paths:
      - 'upflux-webclient/**'  # Only trigger when changes occur in the 'upflux-webclient' folder
  workflow_dispatch:  # Trigger manually from GitHub Actions UI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Specify Node.js version, update as necessary
        registry-url: 'https://npm.pkg.github.com'

    - name: Navigate to the upflux-client folder
      run: cd upflux-client  # Change directory to your React project folder

    - name: Install dependencies
      run: npm install
      working-directory: ./upflux-client  # Ensure npm install runs in the correct folder

    - name: Build npm package
      run: npm run build  # Build your React app
      working-directory: ./upflux-client

    - name: Get the package version
      id: version
      run: echo "PACKAGE_VERSION=$(node -p -e "require('./package.json').version")" >> $GITHUB_ENV
      working-directory: ./upflux-client

    - name: Set up GitHub Packages authentication
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GITHUB_PAT }}" >> ~/.npmrc
      working-directory: ./upflux-client

    # Publish to GitHub Packages if pushing to the main branch
    - name: Publish to GitHub Packages
      if: github.ref == 'refs/heads/main'  # Only runs on merge to the main branch
      run: |
        npm version patch -m "Release version %s"  # Adjust to "minor" or "major" if necessary
        npm publish
      working-directory: ./upflux-client
      env:
        NODE_AUTH_TOKEN: ${{ secrets.MY_GITHUB_PAT }}

    # If not on the main branch, upload build as an artifact
    - name: Upload build directory as an artifact
      if: github.ref != 'refs/heads/main'  # Runs if not on the main branch or on manual trigger
      uses: actions/upload-artifact@v3
      with:
        name: react-build
        path: ./upflux-client/build  # Path to the build directory of your React app

    - name: Display version summary
      run: echo "The package version is ${{ env.PACKAGE_VERSION }}."

